eureka:
  client:
    serviceUrl:
#      defaultZone: http://localhost:8880/eureka/
      defaultZone: http://140.143.197.165:8880/eureka/
server:
  port: 8888
spring:
  jpa:
    hibernate:
      naming:
        strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  mvc:
    view:
      prefix: /WEB-INF/jsp/build/
      suffix: .jsp
  application:
    name: service-face
  redis:
    host: 140.143.197.165
    password: Qin74654...
    port: 6379
    pool:
      max-idle: 100
      min-idle: 1
      max-active: 1000
      max-wait: -1
  #数据库连接信息
  datasource:
        name: test
        url: jdbc:mysql://127.0.0.1:3306/itmayiedu-member?characterEncoding=UTF-8
        username: root
        password: root
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
  ##activemq连接信息
  activemq:
    broker-url: tcp://140.143.197.165:61616
    in-memory: true
    pool:
      enabled: false
   ##mail连接信息
  mail:
    host: smtp.163.com
    username: yushengjun20180315@163.com
    password: itmayiedu123456
    enable:  true
    smtp:
      auth: true
    starttls:
      enable: true
      required: true  
##email Text
msg: 
  subject: 红红火火恍恍惚惚--邮件信息
  text:  恭喜您的账户{},注册-红红火火恍恍惚惚-成功!
#
##队列
messages:
   queue: messages_queue
#
##face 验证信息
face: 
  apikey: Exo1jfY6Wjrm9cKOfQaEjej6
  secretkey:  Cuju8uiaEefrgqkEZTrA7LSpkksOKnau
  token:  24.96b9c89af8f3180cec5b1d6cda6664e5.2592000.1565163899.282335-16299894


    